add: aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -28,16 +28,16 @@ name: Deploy to Amazon ECS
 
 on:
   push:
-    branches: [ "dev" ]
+    branches: [ "aws/dev" ]
 
 env:
-  AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
-  ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
-  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
-  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
-  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
+  AWS_REGION: eu-central-1                   # set this to your preferred AWS region, e.g. us-west-1
+  ECR_REPOSITORY: public.ecr.aws/q6a9u3z6/dimka9910-projects           # set this to your Amazon ECR repository name
+  ECS_SERVICE: java-web-example-service                 # set this to your Amazon ECS service name
+  ECS_CLUSTER: MyDemoClusterDimka9910                 # set this to your Amazon ECS cluster name
+  ECS_TASK_DEFINITION: java-web-example-task-definition # set this to the path to your Amazon ECS task definition
                                                # file, e.g. .aws/task-definition.json
-  CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
+  CONTAINER_NAME: java-web-example-container           # set this to the name of the container in the
                                                # containerDefinitions section of your task definition
 
 permissions:
@@ -47,9 +47,23 @@ jobs:
   deploy:
     name: Deploy
     runs-on: ubuntu-latest
-    environment: production
 
     steps:
+    - name: Check commit status
+        id: commit-status
+        run: |
+          # Check the status of the Git commit
+          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+          echo "Current status is: $CURRENT_STATUS"
+          while [ "${CURRENT_STATUS^^}" = "PENDING" ]; 
+            do sleep 10; 
+            CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+          done;
+          echo "Current status is: $CURRENT_STATUS"
+          if [ "${CURRENT_STATUS^^}" = "FAILURE" ]; 
+            then echo "Commit status failed. Canceling execution"; 
+            exit 1; 
+          fi
     - name: Checkout
       uses: actions/checkout@v3
 
